amazonProperties:
  #endpointUrl: https://s3.us-east-2.amazonaws.com
  endpointUrl: https://localhost:8001
  accessKey: xxxxxxxx
  secretKey: xxxxxxxxxxxx
  #bucketName: mynk-bucket
  bucketName: bucket1
  directorypathtomock: /home/mayank/tmp/s3mock

cloud.aws.region.auto: true
cloud.aws.region.static: us-east-2

spring:
    servlet:
      multipart:
       max-file-size: -1
       max-request-size: -1