amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: xxxxxxxxxx
  secretKey: xxxxxxxxxx
  bucketName: mynk-bucket



cloud.aws.region.auto: true
cloud.aws.region.static: us-east-2

spring:
    servlet:
      multipart:
       max-file-size: -1
       max-request-size: -1
